server:
  port:8888

spring:
  application:
    name:api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
        - uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: HOTEL-SERVICE
        - uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**